# Generated by Django 3.1.7 on 2021-03-25 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210324_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='requestType',
            field=models.CharField(choices=[('Join Event', 'Join Event'), ('Organizer Promotion', 'Organizer Promotion')], default='Join Event', max_length=30, null=True),
        ),
    ]
