# Generated by Django 3.1.7 on 2021-03-25 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20210325_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='requestType',
            field=models.CharField(choices=[('Join Event', 'Join Event'), ('Promote to Organizer', 'Promote to Organizer')], default='Join Event', max_length=30, null=True),
        ),
    ]
