# Generated by Django 3.1.7 on 2021-03-25 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20210325_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='requestType',
            field=models.CharField(choices=[('Join Event', 'Join Event'), ('Organizer Request', 'Organizer Request')], default='Join Event', max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='Administrator',
        ),
    ]
