# Generated by Django 3.1.7 on 2021-03-25 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('account', '0008_auto_20210325_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('admin', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('event', models.ManyToManyField(blank=True, to='account.Event')),
            ],
        ),
    ]
