# Generated by Django 3.1.7 on 2021-03-25 08:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20210325_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 25, 8, 58, 30, 102719, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 25, 8, 58, 30, 102719, tzinfo=utc), null=True),
        ),
    ]
