# Generated by Django 3.1.7 on 2021-03-25 15:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20210325_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 3, 25, 15, 14, 57, 763486, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 3, 25, 15, 14, 57, 763486, tzinfo=utc), null=True),
        ),
    ]
