# Generated by Django 3.1.7 on 2021-03-26 04:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_auto_20210326_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 3, 26, 4, 19, 14, 971859, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 3, 26, 4, 19, 14, 971859, tzinfo=utc), null=True),
        ),
    ]
