# Generated by Django 3.1.4 on 2021-03-24 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='status',
            field=models.CharField(choices=[('Reviewing', 'Reviewing'), ('Accept', 'Accept'), ('Decline', 'Decline')], default='Reviewing', max_length=30, null=True),
        ),
    ]
